#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export j="$DIR/bin/astral.4.7.6.a.jar"

if [ $# -lt 2 ]; then 
 echo "USAGE: $0 input output [extra trees]"
 exit 1;
fi 

in=$1
shift
out=$1
shift
p=$1
shift

if [ -s $out ]; then
  echo "Ouput files exists. Refusing to rerun. "
  exit 0;
fi

java -jar $j -i $in -o $out -p $p $* 1>$out.astral.out 2>$out.astral.err

test "$?" != "0" && exit 1


echo ASTRAL Done. Output at: $out
