#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export j="$DIR/bin/astral.3.1.1.jar"
export lib="$DIR/bin/lib/main.jar"

if [ $# -lt 2 ]; then 
 echo "USAGE: $0 input output [extra trees]"
 exit 1;
fi 

out=$2

if [ -s $out ]; then
  echo "Ouput files exists. Refusing to rerun. "
  exit 0;
fi

ext=""
if [ $# == 4 ]; then
  ext="-e $4"
fi

inn=`mktemp`
nw_topology -I $1 > $inn
arb_resolve_polytomies.py $inn
in=$inn.resolved

java -classpath $j:$lib phylonet.coalescent.CommandLine -wq -i $in -o $out $ext 1>$out.astral.out 2>$out.astral.err

test "$?" != "0" && exit 1


echo ASTRAL Done. Output at: $out
